# Generated by Django 5.0.14 on 2026-05-17 08:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemIssueReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reporter_role",
                    models.CharField(
                        choices=[
                            ("SYSTEM_ADMIN", "System Admin"),
                            ("SCHOOL_ADMIN", "School Admin"),
                            ("USER", "User"),
                        ],
                        default="USER",
                        max_length=50,
                    ),
                ),
                (
                    "tenant_domain",
                    models.CharField(
                        blank=True,
                        help_text="The tenant where the issue occurred",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the issue"),
                ),
                (
                    "browser_info",
                    models.TextField(
                        blank=True,
                        help_text="Diagnostic context (e.g., user agent)",
                        null=True,
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
