# Generated by Django 5.0.14 on 2026-05-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="logo_url",
            field=models.URLField(
                blank=True, help_text="URL to the university's logo", null=True
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="primary_color",
            field=models.CharField(
                default="#22c55e", help_text="Hex code for primary color", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="secondary_color",
            field=models.CharField(
                default="#16a34a",
                help_text="Hex code for secondary color",
                max_length=7,
            ),
        ),
    ]
