# Generated by Django 5.0.14 on 2026-05-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0002_university_logo_url_university_primary_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="university",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
