# Generated by Django 5.0.14 on 2026-05-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_deleted_at_university_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='background_image_url',
            field=models.URLField(blank=True, help_text='Hero image on the tenant login page', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, help_text='Short description shown on the login page'),
        ),
        migrations.AddField(
            model_name='university',
            name='share_logs_with_superuser',
            field=models.BooleanField(default=True, help_text="Allow platform superadmins to see this tenant's audit logs"),
        ),
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='primary_color',
            field=models.CharField(default='#22c55e', max_length=7),
        ),
        migrations.AlterField(
            model_name='university',
            name='secondary_color',
            field=models.CharField(default='#16a34a', max_length=7),
        ),
    ]
