# Generated by Django 5.0.14 on 2026-05-14 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("universities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("abstract", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONCEPT_SUBMITTED", "Concept Submitted"),
                            ("DEPARTMENT_REVIEW", "Department Review"),
                            ("DEPARTMENT_APPROVED", "Department Approved"),
                            ("SUPERVISOR_ASSIGNED", "Supervisor Assigned"),
                            ("UNDER_SUPERVISION", "Under Supervision"),
                            ("PROPOSAL_SUBMITTED", "Proposal Submitted"),
                            ("SCHOOL_REVIEW", "School Review"),
                            ("SCHOOL_APPROVED", "School Approved"),
                            ("ETHICS_REVIEW", "Ethics Review"),
                            ("ETHICS_APPROVED", "Ethics Approved"),
                            ("RESEARCH_REGISTERED", "Research Registered"),
                            ("EXTERNAL_REVIEW", "External Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "ai_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI calculated quality/integrity score",
                        null=True,
                    ),
                ),
                ("plagiarism_score", models.FloatField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="universities.university",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
