# Generated by Django 5.0.14 on 2026-05-17 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0001_initial"),
        ("universities", "0002_university_logo_url_university_primary_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="state",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("CONCEPT_SUBMITTED", "Concept Submitted"),
                    ("DEPARTMENT_REVIEW", "Department Review"),
                    ("DEPARTMENT_APPROVED", "Department Approved"),
                    ("SUPERVISOR_ASSIGNED", "Supervisor Assigned"),
                    ("UNDER_SUPERVISION", "Under Supervision"),
                    ("PROPOSAL_SUBMITTED", "Proposal Submitted"),
                    ("SCHOOL_REVIEW", "School Review"),
                    ("SCHOOL_APPROVED", "School Approved"),
                    ("ETHICS_REVIEW", "Ethics Review"),
                    ("ETHICS_APPROVED", "Ethics Approved"),
                    ("RESEARCH_REGISTERED", "Research Registered"),
                    ("EXTERNAL_REVIEW", "External Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="title",
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["university", "state"], name="proposals_p_univers_ad34e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["student", "state"], name="proposals_p_student_8c7804_idx"
            ),
        ),
    ]
