# Generated by Django 5.0.14 on 2026-05-17 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0001_initial"),
        ("universities", "0002_university_logo_url_university_primary_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="committee",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPARTMENT", "Department Committee"),
                    ("SCHOOL", "School Committee"),
                    ("ETHICS", "Ethics Committee"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(
                fields=["university", "type", "is_active"],
                name="committees__univers_220bb2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="committeemember",
            index=models.Index(
                fields=["user", "is_active"], name="committees__user_id_e0157a_idx"
            ),
        ),
    ]
