# Generated by Django 5.0.14 on 2026-05-17 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0001_initial"),
        ("proposals", "0002_alter_proposal_state_alter_proposal_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="new_state",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="role",
            field=models.CharField(
                db_index=True,
                help_text="The role the user was acting as during this action",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["proposal", "-created_at"],
                name="audit_logs__proposa_4d4d49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor", "-created_at"], name="audit_logs__actor_i_bca6af_idx"
            ),
        ),
    ]
